// Quartr Workflow Map — data layer
// Extracted verbatim from the original WorkflowMap.jsx so layout/visual code
// can be iterated independently. No semantic changes.
import { Q } from "./tokens.js";

// ─── ICP Config ───────────────────────────────────────────────────────────────
// `periods` defines which time-period tabs each ICP exposes, in display order.
// Sellside follows the workflow-aligned IA from the Sell-Side Navigation PRD
// (Daily + Pre-Earnings / Earnings / Post-Earnings / Non-Earnings) instead of
// the time-based Daily/Weekly/Monthly/Yearly used by IR and Buyside.
export const ICPS = {
  IR: {
    label: "Investor Relations", abbr: "IR", icon: "🏢",
    tagline: "Manage the equity story. Protect the share price.",
    accent: Q.ir, dim: Q.irDim, border: Q.irBorder,
    roles: ["Head of IR", "IR Manager", "IR Officer", "CFO"],
    periods: ["Daily","Weekly","Monthly","Yearly","PreEarnings","EarningsDay","PostEarnings"],
  },
  Buyside: {
    label: "Buyside", abbr: "BUY", icon: "📈",
    tagline: "Find alpha, build conviction, manage risk.",
    accent: Q.buy, dim: Q.buyDim, border: Q.buyBorder,
    roles: ["Portfolio Manager", "Equity Analyst", "Hedge Fund Analyst"],
    periods: ["Daily","Weekly","Monthly","Yearly","PreEarnings","EarningsDay","PostEarnings"],
  },
  Sellside: {
    label: "Sellside", abbr: "SELL", icon: "🔬",
    tagline: "Cover companies, inform clients, move markets.",
    accent: Q.sell, dim: Q.sellDim, border: Q.sellBorder,
    roles: ["Equity Research Analyst", "Research Associate", "Sector Strategist"],
    periods: ["Daily","PreEarnings","EarningsDay","PostEarnings","NonEarnings"],
  },
};

// ─── Quartr Pro Feature Tags ───────────────────────────────────────────────────
export const QF = {
  SEARCH:     "Global Transcript Search",
  SLIDE:      "Slide Search",
  SUMMARY:    "Event Summaries",
  MENTION:    "Mentioned By",
  KEYWORD:    "Keyword Alerts",
  HISTORY:    "History Mode",
  AI:         "AI Chat",
  LIVE_AI:    "AI Chat on Live Events",
  UPLOAD:     "Document Upload",
  TEMPLATE:   "Prompt Templates",
  WATCHLIST:  "Watchlists",
  BOOKMARK:   "Bookmarks & Folders",
  SPLIT:      "Split-View",
  LIVE:       "Live Earnings Calls",
  PRESS:      "Press Releases",
  NAV:        "Event & Document Navigation",
  CHAPTERS:   "Transcript Chapters",
  GOVERNANCE: "Governance Filings",
  MCP:        "Claude MCP",
};

// Period display metadata. NonEarnings is Sellside-only per PRD §5.4.
// EarningsDay carries different framing per ICP — kept generic at the metadata
// layer; section subheadings carry the ICP-specific framing.
export const PERIOD_ICON = { Daily:"🕐", Weekly:"📅", Monthly:"🗓️", Yearly:"🏆", PreEarnings:"📋", EarningsDay:"🎤", PostEarnings:"📬", NonEarnings:"🌐" };
export const PERIOD_LABEL = { Daily:"Daily", Weekly:"Weekly", Monthly:"Monthly", Yearly:"Yearly", PreEarnings:"Pre-Earnings", EarningsDay:"Earnings Day", PostEarnings:"Post-Earnings", NonEarnings:"Non-Earnings" };

// Per-ICP overrides for period labels — used so Sellside reads "Earnings (live)"
// per the PRD while IR/Buyside continue to read "Earnings Day".
export const PERIOD_LABEL_BY_ICP = {
  Sellside: { EarningsDay: "Earnings (live)" },
};
export const periodLabel = (icp, p) => (PERIOD_LABEL_BY_ICP[icp]?.[p]) ?? PERIOD_LABEL[p] ?? p;

// ─── Workflow Data ─────────────────────────────────────────────────────────────
export const WORKFLOWS = {
  IR: {
    Daily: {
      tagline: "Stay ahead of the market — protect the narrative every day",
      goals: ["Market monitoring", "Investor responsiveness", "Competitive awareness"],
      steps: [
        { id:"ir-d1", time:"7–9 AM", icon:"☀️",
          title:"Morning Market & Intelligence Briefing",
          summary:"Check own stock, scan overnight peer filings, review press releases and any mentions of your company across the market",
          tasks:["Stock price & volume check","Pre-market peer announcement scan","Overnight press release & 8-K review","'Mentioned By' feed — who referenced you overnight"],
          quartr:true, features:[QF.MENTION,QF.SUMMARY,QF.PRESS,QF.WATCHLIST],
          pain:"Visiting each competitor's IR site or EDGAR manually to catch overnight filings and mentions wastes 45–60 minutes every morning — and things still get missed.",
          value:"The Watchlist surfaces every event, press release, and filing for your peer set overnight. The 'Mentioned By' feed catches every reference to your company. Event Summaries give you the full earnings digest in seconds — all before the market opens.",
          impact:"high" },
        { id:"ir-d2", time:"9–11 AM", icon:"📧",
          title:"Investor Inbox & CRM Triage",
          summary:"Prioritise investor and analyst emails, log call notes, escalate data requests to finance",
          tasks:["Email priority triage","Talking point drafting","CRM entry & updates","VIP investor flagging"],
          quartr:false },
        { id:"ir-d3", time:"11 AM–1 PM", icon:"🔍",
          title:"Competitive Intelligence Sweep",
          summary:"Monitor what peers are saying, how analysts are framing the sector, flag any narrative risks",
          tasks:["Peer announcement tracking","Keyword alert digest review","Sector theme monitoring","Competitor press release scan"],
          quartr:true, features:[QF.KEYWORD,QF.SEARCH,QF.CHAPTERS,QF.MCP],
          pain:"Finding what a peer CFO said on last quarter's call about a topic your investors will ask about requires manually scrubbing hours of recordings — and risk terms like 'impairment' or 'covenant breach' never get caught at all.",
          value:"Keyword Alerts run passively across 14,000+ companies — firing the moment a tracked term appears on any earnings call. Global Transcript Search finds the exact quote in seconds. Connect via Claude MCP to turn alert hits into structured competitive digests automatically.",
          impact:"high" },
        { id:"ir-d4", time:"1–4 PM", icon:"📞",
          title:"Investor & Analyst Outreach",
          summary:"Conduct investor calls, prep talking points, handle ad-hoc meeting requests",
          tasks:["Investor calls & follow-ups","Talking point updates","Live peer call monitoring","Analyst relationship management"],
          quartr:true, features:[QF.SEARCH,QF.TEMPLATE,QF.AI,QF.LIVE_AI],
          pain:"Preparing a sharp, data-backed position for a surprise investor call in 30 minutes is nearly impossible without a central reference point. And when a key peer is reporting live, there's no way to monitor their call and manage your own agenda simultaneously.",
          value:"Reusable Prompt Templates give instant access to your Q&A framework. AI Chat on Live Events lets you query a peer's earnings call as it's happening — extracting what their CFO just said on your investors' key topic, in real time.",
          impact:"medium" },
        { id:"ir-d5", time:"4:30 PM", icon:"📋",
          title:"End-of-Day Wrap & Management Brief",
          summary:"Compile daily summary of notable events, brief the CFO/CEO, set tomorrow's priorities",
          tasks:["Daily events summary","Management briefing note","CRM finalisation","Next-day agenda"],
          quartr:false },
      ],
    },
    Weekly: {
      tagline: "Synthesise intelligence, align stakeholders, sharpen the narrative",
      goals: ["Investor activity synthesis", "Peer benchmarking", "Management alignment"],
      steps: [
        { id:"ir-w1", time:"Monday", icon:"🤝",
          title:"IR Team Sync & Priority Setting",
          summary:"Recap prior week, set the week's communication priorities, align on the event calendar",
          tasks:["IR team standup","Key events recap","Calendar review","Open items tracking"],
          quartr:false },
        { id:"ir-w2", time:"Tue–Wed", icon:"🏦",
          title:"Peer Intelligence Report",
          summary:"Compile weekly digest of competitor earnings, press releases, investor days, and sector narratives",
          tasks:["Peer announcement & press release aggregation","Key competitor quote extraction","Sector theme tracking","Keyword alert digest review"],
          quartr:true, features:[QF.SEARCH,QF.SLIDE,QF.SUMMARY,QF.PRESS,QF.BOOKMARK,QF.MCP],
          pain:"Building a peer intelligence report means visiting 10–20 IR sites, checking press releases, and manually compiling highlights — easily half a working day.",
          value:"Press releases, transcripts, slides, and event summaries for every peer in one searchable library. Slide Search surfaces competitor visuals. Use Claude MCP to turn the whole digest into a structured briefing automatically — bookmark the best quotes as you go.",
          impact:"high" },
        { id:"ir-w3", time:"Wednesday", icon:"✍️",
          title:"Messaging & Content Refresh",
          summary:"Update FAQs, refresh talking points, review public IR materials for accuracy and competitive positioning",
          tasks:["FAQ and Q&A updates","Talking point refresh","Website IR content review","Narrative consistency check"],
          quartr:true, features:[QF.SLIDE,QF.HISTORY,QF.AI],
          pain:"Knowing whether your investor narrative is best-in-class is nearly impossible without visibility into how top-performing IR teams communicate.",
          value:"Slide Search shows how peer IR teams visually present their story. History Mode tracks how their narratives evolve quarter-over-quarter — a live benchmark.",
          impact:"medium" },
        { id:"ir-w4", time:"Thursday", icon:"🎯",
          title:"Investor Meeting Preparation",
          summary:"Brief management ahead of investor meetings, anticipate tough questions, tailor the story by investor type",
          tasks:["Investor background research","Q&A anticipation prep","Management briefing deck","Talking points by investor type"],
          quartr:true, features:[QF.SEARCH,QF.CHAPTERS,QF.TEMPLATE,QF.AI],
          pain:"Anticipating what a specific investor will challenge you on requires knowing what they've asked management teams across your sector — a question that's impossible to answer without reading hundreds of Q&A sections.",
          value:"Search Q&A sections across all public earnings calls to surface recurring investor pressure points. Transcript Chapters jump straight to Q&A. Ask AI Chat: 'What questions has this investor type asked most persistently in our sector?' — and walk into the meeting prepared.",
          impact:"high" },
        { id:"ir-w5", time:"Friday", icon:"📈",
          title:"Weekly IR Report to CFO/CEO",
          summary:"Compile weekly investor interactions, stock vs. peers, and notable events for leadership",
          tasks:["Investor interaction summary","Stock vs. peer performance","Notable events & themes","Next week outlook"],
          quartr:false },
      ],
    },
    Monthly: {
      tagline: "Own the shareholder base, drive the narrative, protect the premium",
      goals: ["Ownership analysis", "Management reporting", "Materials excellence"],
      steps: [
        { id:"ir-m1", time:"Week 1", icon:"📊",
          title:"Shareholder Base Analysis",
          summary:"Review 13F filings, identify new institutional holders, track position changes and activist risk",
          tasks:["13F institutional ownership review","New holder identification","Position size change tracking","Activist risk screening"],
          quartr:false },
        { id:"ir-m2", time:"Week 2", icon:"⚖️",
          title:"Deep-Dive Peer Benchmarking",
          summary:"Comprehensive peer comparison: messaging, narrative positioning, KPI disclosure, analyst framing",
          tasks:["Peer KPI disclosure review","Transcript theme & language analysis","Narrative benchmarking","Analyst sentiment comparison"],
          quartr:true, features:[QF.SEARCH,QF.SLIDE,QF.HISTORY,QF.AI,QF.MCP],
          pain:"Monthly benchmarking takes days of manual research and is frequently deprioritised because the time cost is prohibitive — which means IR messaging is benchmarked against instinct rather than data.",
          value:"AI Chat runs a peer benchmarking analysis across all comparable transcripts and slides in minutes. History Mode shows exactly how competitor narratives have shifted quarter by quarter. Use Claude MCP to run the analysis directly in your AI environment and output a structured report.",
          impact:"high" },
        { id:"ir-m-narrative", time:"Week 2–3", icon:"🧭",
          title:"Narrative & KPI Audit",
          summary:"Audit your own equity story for drift — track which KPIs you've introduced, dropped, or reframed across the last 6–8 quarters",
          tasks:["Prepared remarks comparison across 8 quarters","KPI foregrounding shift analysis","Language drift detection","Equity story gap identification"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.TEMPLATE,QF.MCP],
          pain:"Equity stories don't fail all at once — they drift. A KPI moves from headline to footnote, a strategic frame quietly shifts. By the time analysts reprice, the signal was already visible in the transcripts for 2–4 quarters.",
          value:"Use AI Chat to review your last 8 earnings transcripts chronologically and flag every instance language shifted from confident to hedged — or vice versa. History Mode maps the full arc in one view. Prompt: 'Compare how [Company] opened prepared remarks in Q1 [Year-2] vs Q1 [Year]. Which KPIs moved to footnote? What new language appeared?' Use Claude MCP to run this audit on a recurring schedule before every earnings cycle.",
          impact:"high" },
        { id:"ir-m3", time:"Wk 2–3", icon:"📋",
          title:"Monthly Management IR Dashboard",
          summary:"Prepare monthly IR dashboard with investor feedback, sentiment, and competitive context for board and CFO",
          tasks:["IR activity KPIs","Stock performance vs. peers","Key investor feedback","Analyst & media sentiment"],
          quartr:true, features:[QF.MENTION,QF.KEYWORD,QF.SUMMARY],
          pain:"Adding meaningful competitive context to management reports requires hours of research that usually gets cut when time is tight.",
          value:"'Mentioned By' feeds directly into your competitive context section. Keyword tracking data shows how often your key themes are being discussed across the market.",
          impact:"medium" },
        { id:"ir-m4", time:"Week 3", icon:"🖊️",
          title:"IR Materials & Investor Deck Update",
          summary:"Refresh investor presentation, update fact sheet, ensure all public IR content is current and compelling",
          tasks:["Investor deck refresh","Fact sheet updates","Website content audit","Press release archive"],
          quartr:true, features:[QF.SLIDE,QF.UPLOAD,QF.AI],
          pain:"Improving IR materials without visibility into how best-in-class IR teams in your sector structure their story means working blind.",
          value:"Upload your deck to AI Chat for instant feedback. Slide Search shows how peers frame similar KPIs and tell their growth story.",
          impact:"medium" },
        { id:"ir-m5", time:"Week 4", icon:"📅",
          title:"Events & Calendar Planning",
          summary:"Manage the IR calendar, confirm conferences and NDR schedules, plan earnings logistics",
          tasks:["Conference & NDR scheduling","Earnings date coordination","Investor day pipeline","Management travel"],
          quartr:false },
      ],
    },
    Yearly: {
      tagline: "The milestones that define the company's investor narrative",
      goals: ["Earnings cycle excellence", "Annual report & AGM", "Investor Day", "Strategic targeting"],
      steps: [
        { id:"ir-y1", time:"Q1 · Jan–Mar", icon:"📄", major:true,
          title:"Annual Report & 10-K Filing",
          summary:"Produce and publish the annual report and 10-K — the cornerstone of investor disclosure",
          tasks:["Annual report narrative","10-K with legal & finance","Investor & media distribution","Website posting"],
          quartr:true, features:[QF.SEARCH,QF.GOVERNANCE,QF.UPLOAD],
          pain:"Structuring a best-in-class annual report without competitive benchmarks on peer disclosure depth and format leads to missed opportunities.",
          value:"Access and compare annual reports and governance filings across your entire peer set. Upload your draft to AI Chat for narrative gap identification.",
          impact:"high" },
        { id:"ir-y2", time:"Q1–Q4 · ×4", icon:"🎤", major:true, isCore:true,
          title:"Earnings Cycle",
          summary:"The highest-stakes recurring IR event — preparation, execution, and distribution of quarterly results",
          tasks:["Earnings script & Q&A prep","Press release production","Slides & visual materials","Earnings call hosting","Transcript & replay distribution","Post-earnings roadshow"],
          quartr:true, features:[QF.SEARCH,QF.TEMPLATE,QF.AI,QF.LIVE_AI,QF.UPLOAD,QF.SUMMARY,QF.LIVE,QF.PRESS,QF.NAV],
          pain:"Each earnings cycle involves weeks of fragmented work: peer transcript research for prep, manual materials distribution, and no way to monitor live peer calls while managing your own. No single source of truth.",
          value:"Every earnings stage accelerated — AI Chat researches peer scripts for Q&A prep; AI Chat on Live Events lets you query peer calls as they happen; Press Releases, slides, and transcripts are unified in one event view via the new navigation; Prompt Templates standardise your workflow; Event Summaries create instant post-call digests.",
          impact:"critical" },
        { id:"ir-y3", time:"Q1–Q2 · Mar–Jun", icon:"🏛️", major:true,
          title:"Annual General Meeting (AGM)",
          summary:"Manage proxy statement, shareholder vote logistics, and the AGM presentation",
          tasks:["Proxy statement drafting","Shareholder vote logistics","AGM presentation materials","Post-AGM communication"],
          quartr:true, features:[QF.GOVERNANCE,QF.SLIDE,QF.UPLOAD],
          pain:"Knowing how to position your AGM and proxy communications relative to peer best practice requires significant manual research.",
          value:"Governance Filings gives direct access to proxy statements across your peer universe. Slide Search surfaces how comparable companies structure their AGM presentations.",
          impact:"medium" },
        { id:"ir-y4", time:"Q2–Q3 · May–Sep", icon:"🌟", major:true, isCore:true,
          title:"Investor Day / Capital Markets Day",
          summary:"The flagship annual IR event — full-day investor event with executive deep-dives and major narrative reset",
          tasks:["Event strategy & multi-exec planning","Re-rating catalyst research","Presentation development","Investor outreach & registration","Materials production & distribution","Live event management","Post-event follow-up"],
          quartr:true, features:[QF.SLIDE,QF.SEARCH,QF.HISTORY,QF.UPLOAD,QF.AI,QF.MCP],
          pain:"Planning a standout Investor Day without visibility into how competitors structure their events, presentations, and narratives is a critical blind spot. And knowing which narrative moves have actually unlocked valuation in your sector requires research most IR teams can't do in time.",
          value:"Study every peer Investor Day — presentations, KPI formats, capital allocation framing — all searchable in Quartr Pro. Use AI Chat to reverse-engineer which narrative moves drove re-ratings in your sector 2–4 quarters before they happened. Upload your draft deck for pre-event stress-testing. Claude MCP lets you run the full analysis in your own AI environment.",
          impact:"critical" },
        { id:"ir-y5", time:"Q3 · Jul–Sep", icon:"🎯", major:false,
          title:"Strategic Investor Targeting",
          summary:"Identify and proactively engage new institutional investors aligned with your equity story",
          tasks:["Target investor identification","Conference strategy","Outreach campaigns","Investor perception studies"],
          quartr:false },
        { id:"ir-y6", time:"Q4 · Oct–Dec", icon:"🗓️", major:false,
          title:"Year-End Strategy & Next Year Planning",
          summary:"Review full-year IR performance, set guidance strategy, build next year's IR plan",
          tasks:["Full-year IR review","Guidance strategy","Next year IR calendar","Budget planning"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.KEYWORD],
          pain:"Strategic IR planning without a panoramic view of how competitive communications have evolved across the year leads to reactive IR.",
          value:"History Mode maps every shift in peer narratives across four quarters. AI Chat synthesises full-year trends to sharpen next year's strategy.",
          impact:"medium" },
      ],
    },
    PreEarnings: {
      tagline: "The two weeks before results — prepare the story, anticipate the pressure",
      goals: ["Script & Q&A preparation", "Peer transcript research", "Materials finalisation"],
      steps: [
        { id:"ir-pre1", time:"T–14", icon:"📚",
          title:"Peer Earnings Research Sprint",
          summary:"Research what peers have said on the topics your investors will push hardest — before you write a single word of your own script",
          tasks:["Peer transcript review for key themes","Competitor Q&A section analysis","Sector narrative mapping","Investor pressure point identification"],
          quartr:true, features:[QF.SEARCH,QF.CHAPTERS,QF.AI,QF.HISTORY],
          pain:"Writing a credible earnings script requires knowing what peers have said on every topic your investors care about — research that takes days without the right tools.",
          value:"Search Q&A sections across your entire peer set to surface every question your sector has faced. Transcript Chapters jump straight to the relevant section. AI Chat maps the investor pressure points in your sector in minutes.",
          impact:"high" },
        { id:"ir-pre2", time:"T–10", icon:"✍️",
          title:"Script & Q&A Preparation",
          summary:"Draft the earnings script, prepare the Q&A document, and pressure-test both against the toughest investor questions",
          tasks:["CEO/CFO prepared remarks draft","Q&A document build","Talking point alignment with finance","Management briefing sessions"],
          quartr:true, features:[QF.AI,QF.TEMPLATE,QF.UPLOAD,QF.MCP],
          pain:"The Q&A document is only as good as your ability to anticipate the questions — which requires systematic research most IR teams don't have time to do properly.",
          value:"Upload draft script to AI Chat for gap analysis against what peers have covered. Prompt Templates standardise your Q&A framework so nothing gets missed. Claude MCP can run the full Q&A anticipation analysis on a recurring pre-earnings schedule.",
          impact:"critical" },
        { id:"ir-pre3", time:"T–7", icon:"📋",
          title:"Press Release & Materials Finalisation",
          summary:"Finalise the press release, earnings slides, and all supplemental materials — aligned with the script and reviewed against peer best practice",
          tasks:["Press release drafting & legal review","Earnings slides finalisation","Supplemental data package","IR website preparation"],
          quartr:true, features:[QF.SLIDE,QF.PRESS,QF.AI,QF.UPLOAD],
          pain:"Finalising IR materials without a view of how best-in-class peers structure their press releases and earnings slides means working blind on the most visible output of the quarter.",
          value:"Slide Search shows exactly how peers frame their most important KPIs. Upload your press release draft to AI Chat for narrative consistency check against your script and prior disclosures.",
          impact:"high" },
        { id:"ir-pre4", time:"T–3", icon:"🎯",
          title:"Management Briefing & Dry Run",
          summary:"Final management briefing, Q&A dry run, and logistics confirmation for earnings day",
          tasks:["Management Q&A dry run","Logistics & dial-in confirmation","Investor notification","Board / audit committee sign-off"],
          quartr:false },
      ],
    },
    EarningsDay: {
      tagline: "From press release to post-call roadshow — execute flawlessly",
      goals: ["Flawless call execution", "Real-time peer monitoring", "Post-call distribution"],
      steps: [
        { id:"ir-ed1", time:"Pre-Market", icon:"⚡",
          title:"Press Release Distribution & Opening Setup",
          summary:"Publish the press release, confirm all logistics, and monitor the market reaction as results go live",
          tasks:["Press release distribution via wire","IR website update","Management briefing on pre-market reaction","Dial-in and webcast confirmation"],
          quartr:true, features:[QF.PRESS,QF.WATCHLIST,QF.KEYWORD],
          pain:"The moment a press release drops, the market reacts — and you need to be monitoring peer reactions and investor sentiment simultaneously while managing logistics.",
          value:"Your Watchlist shows how peers and analysts are reacting in real time. Keyword Alerts catch any unexpected references to your press release across the market immediately.",
          impact:"high" },
        { id:"ir-ed2", time:"Call Live", icon:"🎤",
          title:"Earnings Call Hosting",
          summary:"Host the live earnings call — manage the prepared remarks, moderate Q&A, and track what's landing with analysts",
          tasks:["Live call hosting & moderation","Q&A facilitation","Management support","Key analyst question tracking"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.NAV],
          pain:"Hosting the call while simultaneously tracking which questions aren't being answered convincingly is nearly impossible in real time.",
          value:"AI Chat on Live Events lets a second team member monitor the live transcript in real time — flagging deflective answers and surfacing follow-up opportunities as the call progresses.",
          impact:"critical" },
        { id:"ir-ed3", time:"Post-Call", icon:"📡",
          title:"Peer Call Monitoring",
          summary:"Monitor what peers reporting the same day are saying — catch any narrative that could affect your investor conversations",
          tasks:["Peer call live monitoring","Competitor guidance comparison","Sector narrative check","Investor talking point updates"],
          quartr:true, features:[QF.LIVE_AI,QF.LIVE,QF.SUMMARY,QF.KEYWORD],
          pain:"On a busy earnings day, multiple peers often report simultaneously — what a competitor says about sector demand directly affects how investors read your results.",
          value:"AI Chat on Live Events lets you query a peer's live call without attending it. Event Summaries process any call you couldn't monitor in real time. Keyword Alerts catch any competitor reference to themes that overlap with your narrative.",
          impact:"high" },
        { id:"ir-ed4", time:"Same Day", icon:"📋",
          title:"Transcript Distribution & Post-Call Wrap",
          summary:"Distribute transcript and replay, log analyst reactions, and prepare the immediate investor follow-up list",
          tasks:["Transcript & replay distribution","IR website posting","Analyst reaction logging","Follow-up investor list"],
          quartr:true, features:[QF.SUMMARY,QF.NAV],
          pain:"Getting the transcript and replay live quickly while simultaneously tracking analyst reactions and fielding the first investor calls is a coordination challenge.",
          value:"Event Summaries create an instant post-call digest to share with management and board. The unified Event Navigation makes transcript, slides, and press release immediately accessible to investors via Quartr.",
          impact:"medium" },
      ],
    },
    PostEarnings: {
      tagline: "Close the loop — investor follow-up, narrative refresh, and lessons captured",
      goals: ["Investor follow-up", "Narrative refresh", "Management reporting"],
      steps: [
        { id:"ir-post1", time:"T+1–3", icon:"📞",
          title:"Post-Call Investor Follow-Up",
          summary:"Field investor and analyst follow-up calls, address any questions the Q&A didn't fully resolve, and gather feedback on how the message landed",
          tasks:["Investor follow-up calls","Analyst feedback gathering","Management debrief on message reception","CRM updates"],
          quartr:true, features:[QF.AI,QF.CHAPTERS,QF.SUMMARY],
          pain:"Investors call back with follow-up questions that go deeper than what was covered on the call — answering accurately requires finding exact quotes quickly.",
          value:"AI Chat surfaces any transcript quote on demand during live investor calls. Transcript Chapters jump to the exact section. Event Summaries give you the structured post-call digest to share with management.",
          impact:"high" },
        { id:"ir-post2", time:"T+3–7", icon:"🗺️",
          title:"Post-Earnings Roadshow",
          summary:"Conduct the post-earnings investor roadshow — one-on-ones and group meetings to deepen conviction among current and target holders",
          tasks:["NDR scheduling & logistics","Investor meeting prep","Talking point updates based on call feedback","New investor targeting"],
          quartr:true, features:[QF.AI,QF.TEMPLATE,QF.SEARCH],
          pain:"Roadshow prep after earnings requires updating talking points based on what landed well on the call — and knowing which investor questions to expect.",
          value:"AI Chat identifies the top investor themes from your Q&A and peer calls to sharpen your roadshow narrative. Prompt Templates update your talking point framework with this quarter's key messages.",
          impact:"high" },
        { id:"ir-post3", time:"T+7–14", icon:"🧭",
          title:"Narrative Audit & Message Refresh",
          summary:"Audit the earnings call for narrative drift, refresh IR materials, and update the equity story for next quarter's cycle",
          tasks:["Transcript narrative review","KPI foregrounding check","IR website & fact sheet update","FAQ and Q&A document refresh"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.MCP,QF.TEMPLATE],
          pain:"Most IR teams don't systematically audit their own call after it happens — which means narrative drift accumulates quarter by quarter without anyone catching it.",
          value:"AI Chat reviews your transcript and compares it to prior quarters — flagging any language drift, KPIs that moved to footnote, or hedging that crept in. Prompt: 'Compare how we described [topic] this quarter vs. the last 4 calls. Where has language shifted?'",
          impact:"high" },
        { id:"ir-post4", time:"T+10–21", icon:"📋",
          title:"Post-Earnings Management Report",
          summary:"Compile the post-earnings IR report for the CFO, CEO, and board — investor feedback, message reception, and competitive context",
          tasks:["Investor feedback synthesis","Analyst sentiment summary","Stock performance vs. peers","Competitive narrative context","Next quarter priorities"],
          quartr:true, features:[QF.MENTION,QF.SUMMARY,QF.AI,QF.KEYWORD],
          pain:"Adding meaningful competitive context to post-earnings management reports requires hours of research that usually gets cut when there's pressure to move on.",
          value:"'Mentioned By' shows every analyst and investor reference to your company post-earnings. AI Chat synthesises the competitive narrative context. Keyword tracking shows whether your key themes are gaining or losing ground across the market.",
          impact:"medium" },
      ],
    },
  },

  Buyside: {
    Daily: {
      tagline: "Find signal, build conviction, stay ahead of every name you own",
      goals: ["Portfolio monitoring", "Earnings intelligence", "New idea sourcing"],
      steps: [
        { id:"buy-d1", time:"Pre-Market", icon:"⚡",
          title:"Overnight Earnings & Portfolio Briefing",
          summary:"Check portfolio company news, overnight earnings results, press releases and filings from names you're monitoring",
          tasks:["Portfolio company news scan","Overnight earnings results & press releases","Keyword alert digest","Pre-market price & volume for holdings"],
          quartr:true, features:[QF.LIVE,QF.SUMMARY,QF.PRESS,QF.WATCHLIST,QF.KEYWORD],
          pain:"Tracking overnight earnings, press releases, and material filings across a diversified portfolio means checking dozens of sites before market open — almost no one does this comprehensively.",
          value:"Your Watchlist surfaces every earnings event, press release, and filing for your holdings overnight. Keyword Alerts catch sector signals you weren't actively looking for. Event Summaries give you a structured digest of each result before you've opened Bloomberg.",
          impact:"high" },
        { id:"buy-d2", time:"9:30–12 PM", icon:"📡",
          title:"Live Earnings Call Coverage",
          summary:"Follow live calls for portfolio and watchlist companies — extract key data points, management tone, and guidance changes in real time",
          tasks:["Live call attendance (audio + transcript)","Real-time AI questioning on live transcript","KPI & guidance extraction","Press release vs. prepared remarks comparison"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SPLIT,QF.PRESS,QF.NAV,QF.CHAPTERS],
          pain:"Following a live call while reading the press release, comparing to model, and extracting key quotes is a 3-screen exercise — something always gets missed, especially when covering two calls simultaneously.",
          value:"AI Chat on Live Events lets you ask questions directly on the live transcript as management speaks — 'What guidance did they give on margins?' without waiting for the replay. Split-View and the new Event Navigation keep the live transcript, press release, and slides open together in one unified workspace.",
          impact:"critical" },
        { id:"buy-d3", time:"Midday", icon:"🔍",
          title:"Post-Earnings Deep-Dive & Model Update",
          summary:"Process earnings results, extract key metrics, compare to prior quarters, update financial model",
          tasks:["KPI extraction from transcript & slides","Actuals vs. prior quarter comparison","Model update & estimate revision","Conviction rating review"],
          quartr:true, features:[QF.AI,QF.UPLOAD,QF.SEARCH,QF.SUMMARY],
          pain:"Extracting specific KPIs, management commentary changes, and comparable quotes from dense transcripts takes hours of manual reading.",
          value:"AI Chat extracts any KPI, ratio, or management quote on demand. Upload your earnings preview and compare it line-by-line to the actual transcript — instantly identify where you were wrong.",
          impact:"high" },
        { id:"buy-d4", time:"Afternoon", icon:"💡",
          title:"New Idea Research & Thesis Building",
          summary:"Research new investment ideas, build initial understanding of a company's narrative and competitive position",
          tasks:["Company earnings history review","Peer positioning analysis","Management communication style assessment","Initial thesis framework"],
          quartr:true, features:[QF.SEARCH,QF.HISTORY,QF.AI,QF.SLIDE],
          pain:"Getting up to speed on a new name requires reading years of transcripts, filings, and presentations — a multi-day process with traditional tools.",
          value:"AI Chat compresses years of transcripts into a structured briefing in minutes. History Mode shows how the company's key messages and KPIs have evolved — the thesis trajectory in one view.",
          impact:"high" },
        { id:"buy-d5", time:"EOD", icon:"📋",
          title:"Portfolio Review & IC Prep",
          summary:"Review portfolio positions, flag conviction changes, prep for morning IC discussion",
          tasks:["Position review & sizing","Conviction change flagging","IC discussion prep","Risk review"],
          quartr:false },
      ],
    },
    Weekly: {
      tagline: "Stress-test every position and find the next great trade",
      goals: ["Thesis stress-testing", "Earnings week management", "Sector intelligence"],
      steps: [
        { id:"buy-w1", time:"Monday", icon:"📋",
          title:"Portfolio & Earnings Calendar Review",
          summary:"Review the week's earnings calendar across holdings and watchlist, set research priorities",
          tasks:["Earnings calendar review","Portfolio P&L & attribution","Research priority setting","IC / PM briefing"],
          quartr:false },
        { id:"buy-w2", time:"Tue–Thu", icon:"📡",
          title:"Earnings Week Coverage",
          summary:"Cover earnings calls across portfolio and watchlist; process results fast and update models",
          tasks:["Multi-company live call coverage","Real-time AI questioning on live calls","Rapid result processing","Actuals vs. estimates comparison","Cross-company theme extraction"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SPLIT,QF.PRESS,QF.NAV,QF.SUMMARY,QF.CHAPTERS,QF.TEMPLATE],
          pain:"Earnings season is an information avalanche — covering 10+ companies in a week while processing results deeply is practically impossible without workflow automation.",
          value:"AI Chat on Live Events lets you extract answers from any call in real time — no waiting for the replay. Press Releases sit alongside transcripts and slides in the new unified event view. Event Summaries process each result automatically. Prompt Templates standardise your post-earnings analysis so nothing gets missed.",
          impact:"critical" },
        { id:"buy-w3", time:"Wednesday", icon:"🔬",
          title:"Sellside Research Interrogation",
          summary:"Digest sellside notes on your holdings; challenge consensus assumptions with primary source data",
          tasks:["Sellside note review","Consensus assumption challenge","Primary source verification","Counter-thesis identification"],
          quartr:true, features:[QF.UPLOAD,QF.AI,QF.SEARCH],
          pain:"Sellside research is dense and consensus-anchored. Challenging it with primary sources requires digging through transcripts that don't cross-reference each other.",
          value:"Upload any sellside report to AI Chat. Ask it to identify where the analyst's assumptions diverge from what management has actually said — with transcript citations.",
          impact:"high" },
        { id:"buy-w4", time:"Thursday", icon:"🌐",
          title:"Sector & Supply Chain Intelligence",
          summary:"Track what companies across your sector's ecosystem are signalling — customers, suppliers, competitors",
          tasks:["Keyword alert digest review","Customer company call review","Supplier commentary extraction","Competitor management tone analysis","Sector theme triangulation"],
          quartr:true, features:[QF.MENTION,QF.KEYWORD,QF.SEARCH,QF.MCP],
          pain:"Understanding the full supply chain signal requires monitoring dozens of companies across multiple sub-sectors — impossible to do manually at scale. And the most important signals — a competitor namedrop, a 'buyback' announcement, a capex pivot — are buried in calls you didn't cover.",
          value:"Keyword Alerts run passively all week across 14,000+ companies — surfacing competitor namedrops, capital allocation signals, and risk terms the moment they appear in any earnings call. 'Mentioned By' catches every time your holdings are referenced. Claude MCP turns the week's alert hits into a structured sector intelligence digest automatically.",
          impact:"high" },
        { id:"buy-w-keyword", time:"Ongoing", icon:"⚙️",
          title:"Automated Keyword Intelligence Feed",
          summary:"Passive background monitoring of sectors, themes, and risk signals across the full universe — running continuously while you focus elsewhere",
          tasks:["Keyword alert configuration & maintenance","Risk term monitoring (impairment, covenant, restatement)","Capital allocation signal tracking (buyback, M&A, deleveraging)","Sector theme feed (sector-specific language: ARR, GLP-1, reshoring)","Weekly alert digest review"],
          quartr:true, features:[QF.KEYWORD,QF.MENTION,QF.WATCHLIST,QF.MCP],
          pain:"~10,000 earnings calls hit the wire every quarter. Buried inside are exact signals that move portfolios: a competitor namedrop, a 'restatement' whisper, a surprise capex pivot. Nobody has time to listen to all of them — which means most signals are caught from a sellside note rather than the source.",
          value:"Configure Keyword Alerts for risk terms, capital allocation signals, competitor names, and sector-specific themes. Quartr monitors every call across 14,000+ companies and delivers alerts the moment any tracked term enters the public domain — straight from management, before the analyst note is written. Pair with Claude MCP to automatically convert alert hits into structured investment digests. This runs in the background all week, compounding intelligence passively.",
          impact:"high" },
        { id:"buy-w5", time:"Friday", icon:"🎯",
          title:"Weekly Thesis Review & IC Presentation",
          summary:"Consolidate week's research, update conviction ratings, present new ideas or changes to IC",
          tasks:["Conviction rating updates","New idea presentation prep","Risk factor refresh","Next week research priorities"],
          quartr:false },
      ],
    },
    Monthly: {
      tagline: "Portfolio construction, risk management, and big-picture thesis work",
      goals: ["Portfolio construction", "Thesis stress-testing", "New idea generation"],
      steps: [
        { id:"buy-m1", time:"Week 1", icon:"🗂️",
          title:"Portfolio Attribution & Review",
          summary:"Deep-dive into what drove returns, which theses played out, and where the misses were",
          tasks:["Attribution analysis","Thesis hit-rate review","Position sizing assessment","Drawdown postmortem"],
          quartr:false },
        { id:"buy-m2", time:"Week 2", icon:"🔬",
          title:"Deep Research on Core Positions",
          summary:"Monthly deep-dive into highest-conviction positions — re-reading transcripts, checking narrative drift",
          tasks:["Multi-year transcript review","Management tone & consistency check","KPI foregrounding shift audit","Thesis vs. reality gap analysis"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.SEARCH,QF.BOOKMARK,QF.MCP],
          pain:"Re-reading transcripts from 6–8 quarters back to check for narrative drift or management credibility issues takes 2–3 full days per company. KPI definition changes go undetected and quietly break models.",
          value:"History Mode shows KPI and narrative evolution across every quarter in a single timeline. AI Chat surfaces every instance management changed their language on a given topic — and flags when a KPI definition shifted. Use Claude MCP to automate monthly narrative drift checks across your entire book.",
          impact:"high" },
        { id:"buy-m3", time:"Wk 2–3", icon:"💡",
          title:"New Idea Generation & Screening",
          summary:"Systematically screen for new ideas — sector deep-dives, thematic research, event-driven opportunities",
          tasks:["Sector transcript screening","Thematic search across companies","Management quality assessment","Initial financial screen"],
          quartr:true, features:[QF.SEARCH,QF.SLIDE,QF.AI,QF.SUMMARY],
          pain:"Screening for new ideas requires reading enough about each company to form a view — there are thousands of companies across relevant sectors.",
          value:"AI Chat compresses any company's multi-year transcript history into a structured investment brief in minutes. Slide Search finds every company that has mentioned a specific growth theme.",
          impact:"high" },
        { id:"buy-m4", time:"Week 3", icon:"📊",
          title:"ESG & Governance Deep-Dive",
          summary:"Review governance practices, compensation structures, and any activist or proxy-related dynamics",
          tasks:["Proxy filing review","Compensation structure analysis","Board composition check","Activist monitoring"],
          quartr:true, features:[QF.GOVERNANCE,QF.MENTION,QF.SEARCH],
          pain:"Governance analysis requires digging through proxy statements — documents that are notoriously hard to parse and cross-reference.",
          value:"Governance Filings gives structured access to proxy statements across all holdings. 'Mentioned By' flags any activist or governance-related commentary from external sources.",
          impact:"medium" },
        { id:"buy-m5", time:"Week 4", icon:"📅",
          title:"Monthly IC Reporting & Strategy",
          summary:"Present monthly portfolio review to fund management; flag thesis changes, new ideas, and risk updates",
          tasks:["Portfolio review deck","New ideas presentation","Risk & scenario update","Outlook & positioning"],
          quartr:false },
      ],
    },
    Yearly: {
      tagline: "The rhythms that shape annual performance and long-term alpha",
      goals: ["Full earnings cycle", "Investor Day season", "Annual portfolio construction"],
      steps: [
        { id:"buy-y1", time:"Q1–Q4 · ×4", icon:"🎤", major:true, isCore:true,
          title:"Earnings Season (×4/year)",
          summary:"The dominant recurring cycle — processing results across the portfolio efficiently and extracting the real signal",
          tasks:["Multi-company call coverage","Real-time AI Chat on live calls","Rapid earnings processing","Actuals vs. model comparison","Post-earnings position review","Guidance extraction"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SUMMARY,QF.SPLIT,QF.PRESS,QF.NAV,QF.AI,QF.UPLOAD,QF.TEMPLATE],
          pain:"Four earnings seasons define the year. Without an efficient workflow, analysts are drowning in calls and notes — and the signal gets buried in noise.",
          value:"AI Chat on Live Events gives you answers from any call as management speaks. Press Releases, transcripts, and slides unified in one event view. Real-time transcripts, AI Event Summaries, and earnings preview vs. actual comparison — Quartr Pro covers the full earnings workflow in one place.",
          impact:"critical" },
        { id:"buy-y2", time:"Q2–Q3 · May–Sep", icon:"🌟", major:true, isCore:true,
          title:"Investor Day Season",
          summary:"Management teams lay out their multi-year strategy — the richest information event of the year",
          tasks:["Investor Day attendance (live + real-time AI)","Long-term guidance extraction","Management quality assessment","Thesis confirmation or challenge"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SLIDE,QF.NAV,QF.AI,QF.SUMMARY,QF.BOOKMARK],
          pain:"Investor Days are the richest information events of the year — hours of management presentations that are impossible to process efficiently without the right tools. Most PMs miss half the CMDs they want to cover.",
          value:"Attend live with AI Chat answering your questions in real time as management presents. Every Investor Day — live audio, slides, transcript, and press releases — in one unified view. AI Chat extracts multi-year targets and capital allocation commitments in minutes from the replay if you missed it.",
          impact:"critical" },
        { id:"buy-y3", time:"Q1 · Jan–Mar", icon:"📄", major:true,
          title:"Annual Report Season",
          summary:"Annual reports and 20-F filings provide the deepest management commentary — a qualitative goldmine",
          tasks:["Annual report / 20-F deep-read","Risk factor analysis","MD&A commentary extraction","Year-on-year comparison"],
          quartr:true, features:[QF.GOVERNANCE,QF.AI,QF.UPLOAD,QF.HISTORY],
          pain:"Annual reports are dense — extracting key management insights and comparing them year-on-year requires hours of careful reading per company.",
          value:"AI Chat extracts and synthesises the key narrative from annual reports and 20-Fs in minutes. History Mode shows how risk disclosures and MD&A language have changed.",
          impact:"high" },
        { id:"buy-y4", time:"Q3 · Jul–Sep", icon:"🌍", major:false,
          title:"Conference Season",
          summary:"Bank-hosted conferences where management teams make off-schedule presentations — an underused source",
          tasks:["Conference presentation review","Management fireside tracking","Cross-company theme extraction","Meeting intel processing"],
          quartr:true, features:[QF.LIVE,QF.SEARCH,QF.SUMMARY],
          pain:"Management teams often say things in conference presentations they don't say on earnings calls — tracking dozens of appearances manually is impractical.",
          value:"Quartr captures conference presentations and firesides from 14,000+ companies. Event Summaries mean you never miss a signal from a presentation you couldn't attend.",
          impact:"medium" },
        { id:"buy-y5", time:"Q4 · Oct–Dec", icon:"🗓️", major:false,
          title:"Annual Portfolio Construction & Outlook",
          summary:"Build next year's portfolio, set position sizing, identify new sectors or themes for the year ahead",
          tasks:["Annual portfolio review","Thesis prioritisation","New sector/theme identification","Sizing & risk framework"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.KEYWORD],
          pain:"Making high-conviction annual portfolio decisions without a comprehensive view of how each company's narrative has evolved across the year is flying blind.",
          value:"History Mode maps the full-year narrative evolution for every holding. AI Chat synthesises four quarters of earnings calls into the key themes and thesis confirmation points.",
          impact:"medium" },
      ],
    },
    PreEarnings: {
      tagline: "Build the conviction before results drop — preview, model, position",
      goals: ["Earnings preview", "Model finalisation", "Position review"],
      steps: [
        { id:"buy-pre1", time:"T–14", icon:"📚",
          title:"Historical Research & Thesis Review",
          summary:"Re-read the last 2–3 quarters' transcripts for each upcoming name — validate the thesis and identify the key questions this quarter needs to answer",
          tasks:["Recent transcript review","KPI trend validation","Thesis vs. current setup gap analysis","Key question identification"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.CHAPTERS,QF.BOOKMARK],
          pain:"Properly re-reading 2–3 quarters of transcripts for every name reporting in the next two weeks takes a week — and it still gets done superficially.",
          value:"History Mode shows the full narrative and KPI evolution across the last 8 quarters in one view. AI Chat compresses a multi-quarter transcript review into a structured briefing per name in minutes.",
          impact:"high" },
        { id:"buy-pre2", time:"T–10", icon:"📊",
          title:"Earnings Preview & Model Finalisation",
          summary:"Lock estimates, build the earnings day scenario framework, and publish the earnings preview for IC",
          tasks:["Estimate finalisation","Bull / base / bear scenario build","Management guidance review","Earnings preview for IC"],
          quartr:true, features:[QF.AI,QF.SEARCH,QF.HISTORY,QF.TEMPLATE],
          pain:"Building a credible earnings preview requires knowing exactly what management guided last quarter and where the language around each KPI has shifted.",
          value:"AI Chat extracts every guidance figure and qualifier from the last two calls on demand. History Mode puts guidance evolution in full context. Prompt Templates standardise the preview framework for consistent IC presentation.",
          impact:"high" },
        { id:"buy-pre3", time:"T–5", icon:"⚙️",
          title:"Automated Keyword Setup",
          summary:"Configure Keyword Alerts and Watchlist for the upcoming cycle — ensure you catch every relevant signal across portfolio and sector as results come in",
          tasks:["Watchlist event alert configuration","Sector keyword alert review","Risk term monitoring setup","Earnings calendar confirmation"],
          quartr:true, features:[QF.KEYWORD,QF.WATCHLIST,QF.MENTION,QF.MCP],
          pain:"During earnings season the signal-to-noise ratio collapses — companies across your supply chain are all reporting simultaneously and it's impossible to track everything.",
          value:"Set keyword alerts for key themes, competitor names, and risk terms before the cycle starts. Quartr monitors every call across 14,000+ companies and delivers alerts the moment a tracked term appears — passively, while you focus on your core names.",
          impact:"medium" },
        { id:"buy-pre4", time:"T–3", icon:"🎯",
          title:"Position Sizing Review",
          summary:"Review current position sizes against conviction levels ahead of results — decide where you want to be going into each print",
          tasks:["Conviction vs. position size review","Pre-earnings risk assessment","PM alignment on sizing","Options / hedge review"],
          quartr:false },
      ],
    },
    EarningsDay: {
      tagline: "From first print to updated conviction — speed and accuracy on the day",
      goals: ["Live call coverage", "Real-time extraction", "Same-day model update"],
      steps: [
        { id:"buy-ed1", time:"Pre-Market", icon:"⚡",
          title:"Press Release & Pre-Market Analysis",
          summary:"The moment results drop — extract headline numbers, compare to model, and form the initial read before the call starts",
          tasks:["Press release parsing","Actuals vs. model comparison","Revenue & margin surprise calculation","Initial conviction direction"],
          quartr:true, features:[QF.PRESS,QF.NAV,QF.AI,QF.SUMMARY],
          pain:"The press release drops before market open and you need a clean read before the call starts — while simultaneously checking 2–3 other names reporting the same morning.",
          value:"Press releases sit alongside prior transcripts and slides in one unified event view — no context switching. AI Chat compares actuals to your model framework in seconds. Event Summaries process each result automatically.",
          impact:"critical" },
        { id:"buy-ed2", time:"Call Live", icon:"📡",
          title:"Live Call Coverage with Real-Time AI",
          summary:"Cover the live call — extract guidance, management tone, and Q&A signals in real time using AI Chat on the live transcript",
          tasks:["Live call attendance","Real-time AI questioning on live transcript","Guidance extraction","Q&A signal monitoring","Model update triggers"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SPLIT,QF.CHAPTERS,QF.PRESS,QF.NAV],
          pain:"Following the live call while reading the press release, comparing to model, and extracting key quotes is a 3-screen exercise — something always gets missed when covering multiple calls simultaneously.",
          value:"AI Chat on Live Events lets you ask questions directly on the live transcript as management speaks — 'What guidance did they give on margins?' — without waiting for the replay. Split-View keeps everything in one workspace.",
          impact:"critical" },
        { id:"buy-ed3", time:"Post-Call", icon:"🔍",
          title:"Post-Earnings Deep-Dive & Model Update",
          summary:"Process the full transcript, extract every relevant KPI and comment, and update the financial model",
          tasks:["Full transcript KPI extraction","Actuals vs. preview line-by-line","Model update","Conviction rating revision"],
          quartr:true, features:[QF.AI,QF.UPLOAD,QF.SEARCH,QF.SUMMARY],
          pain:"Extracting specific KPIs, management commentary changes, and comparable quotes from dense transcripts takes hours — by which time the market has already moved.",
          value:"AI Chat extracts any KPI, ratio, or management quote on demand. Upload your earnings preview to compare it line-by-line to the actual transcript — instantly identify every deviation. Model update inputs ready in minutes.",
          impact:"high" },
        { id:"buy-ed4", time:"Same Day", icon:"📋",
          title:"Position & Conviction Update",
          summary:"Update conviction ratings, adjust position sizes if warranted, and prepare the IC discussion for the morning meeting",
          tasks:["Conviction rating update","Position sizing decision","IC morning meeting prep","Risk review"],
          quartr:false },
      ],
    },
    PostEarnings: {
      tagline: "Stress-test the thesis, challenge consensus, update the book",
      goals: ["Thesis stress-testing", "Consensus challenge", "Portfolio update"],
      steps: [
        { id:"buy-post1", time:"T+1–3", icon:"🔬",
          title:"Sellside Research Interrogation",
          summary:"Digest the sellside notes that drop post-earnings — challenge their assumptions against what management actually said",
          tasks:["Sellside note review","Consensus assumption challenge","Primary source verification","Counter-thesis identification"],
          quartr:true, features:[QF.UPLOAD,QF.AI,QF.SEARCH,QF.CHAPTERS],
          pain:"Sellside research drops fast post-earnings and is consensus-anchored. Challenging it with primary sources requires cross-referencing the transcript in a way that's impractical under time pressure.",
          value:"Upload any sellside note to AI Chat. Ask it to identify where the analyst's assumptions diverge from what management actually said — with exact transcript citations.",
          impact:"high" },
        { id:"buy-post2", time:"T+3–7", icon:"🌐",
          title:"Supply Chain & Sector Signal Processing",
          summary:"Process the cross-company signals that emerged during the earnings cycle — customers, suppliers, and competitors",
          tasks:["Keyword alert digest review","Customer commentary extraction","Competitor guidance comparison","Supply chain signal synthesis"],
          quartr:true, features:[QF.KEYWORD,QF.MENTION,QF.SEARCH,QF.MCP],
          pain:"The best signals often come from companies adjacent to your holdings — a customer flagging demand weakness, a supplier calling out capacity constraints — and they're invisible without systematic monitoring.",
          value:"Keyword Alerts have been running all cycle — every relevant cross-company signal is already flagged. 'Mentioned By' catches every reference to your holdings from adjacent companies. Claude MCP synthesises the week's signals into a structured supply chain brief automatically.",
          impact:"high" },
        { id:"buy-post3", time:"T+5–10", icon:"💡",
          title:"Thesis Update & Conviction Review",
          summary:"Systematically update the thesis for every name that reported — identify where conviction has increased, decreased, or where the story has fundamentally changed",
          tasks:["Thesis vs. actuals comparison","Conviction rating update","New information integration","Portfolio rebalancing triggers"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.BOOKMARK,QF.MCP],
          pain:"Updating the thesis for 10–15 names post-earnings while holding 6–8 quarters of context in mind for each is cognitively impossible without a structured workflow.",
          value:"History Mode puts this quarter's results in the full narrative context of the prior 8 quarters per name. AI Chat identifies where management confirmed or undermined the investment thesis. Bookmarked quotes from the cycle build the evidence base for the IC discussion.",
          impact:"high" },
        { id:"buy-post4", time:"T+7–14", icon:"📊",
          title:"New Idea Generation from Earnings Cycle",
          summary:"The earnings cycle surfaces new ideas — companies that surprised, narratives that shifted, sector themes that emerged. Capture them while fresh.",
          tasks:["Positive surprise screening","Narrative shift identification","New theme-driven ideas","Initial position sizing"],
          quartr:true, features:[QF.SEARCH,QF.AI,QF.KEYWORD,QF.SUMMARY],
          pain:"New ideas that emerge from the earnings cycle get lost in the noise unless there's a process to capture them — a company that surprised on a metric you care about, a sector theme that crystallised.",
          value:"Keyword Alerts have already flagged the cross-company themes. AI Chat screens the cycle for positive surprises against your investment criteria. Event Summaries mean you can rapidly review any company that appeared on your radar.",
          impact:"medium" },
      ],
    },
  },

  Sellside: {
    // Daily — non-earnings rhythms. The ~80% of working days that aren't a
    // print. Earnings-day work lives under Earnings (live). Sell-side analysts
    // typically arrive ~7 AM, scan overnight news, contribute to the morning
    // research call, take corporate-access / NDR calls through the day, and
    // pump out modeling, primers, and theme work between client touchpoints.
    Daily: {
      tagline: "The non-earnings day — be useful to clients before the open and after the close",
      goals: ["Pre-market intelligence", "Sales & client mind-share", "Coverage maintenance"],
      steps: [
        { id:"sell-d1", time:"6–7:30 AM", icon:"⚡",
          title:"Pre-Market Sweep",
          summary:"Process overnight headlines, peer filings, and any after-hours releases across the covered universe before the market opens",
          tasks:["Overnight headlines & 8-K scan","Adjacent-sector announcements","Pre-market price action","'Mentioned By' feed across covered names"],
          quartr:true, features:[QF.WATCHLIST,QF.MENTION,QF.PRESS,QF.SUMMARY],
          pain:"Catching every overnight filing, mention, and after-hours release across 15–25 covered names — without missing the one that will define a client conversation today — is the part of the morning that doesn't scale.",
          value:"Watchlists surface every event, press release, and filing for your coverage overnight. The Mentioned By feed catches every company that referenced one of yours. Event Summaries digest the after-hours prints in seconds — all before you sit down for the morning call.",
          impact:"high" },
        { id:"sell-d2", time:"7:30–8:30 AM", icon:"📣",
          title:"Morning Call Pitch & Email Blast",
          summary:"Pitch any high-impact research to the sales team and lock in the day's top talking points so sales can carry them to clients",
          tasks:["Pitch upgrades / downgrades / theme calls","Sharpen the morning email blast","Brief sales on overnight events","Flag the day's top client questions"],
          quartr:true, features:[QF.AI,QF.SEARCH,QF.TEMPLATE],
          pain:"The morning blast goes out before 8 AM. Building a sharp, defensible pitch with the right management quote and prior-quarter context — every single morning — is a treadmill that punishes the team that's slowest.",
          value:"AI Chat with Prompt Templates drafts the morning blast structure off your prior call notes. Global Transcript Search surfaces the exact management quote you need. Sales gets a tighter brief; clients get a sharper email.",
          impact:"high" },
        { id:"sell-d3", time:"9 AM–12 PM", icon:"📞",
          title:"Client Inbounds & NDR Hosting",
          summary:"Handle inbound from PMs and analysts, run management access calls / non-deal roadshows, and own the moments where the relationship lives",
          tasks:["PM / analyst inbound calls","Management one-on-ones (NDRs)","Bespoke client follow-ups","Channel-check sourcing"],
          quartr:true, features:[QF.SEARCH,QF.CHAPTERS,QF.AI,QF.HISTORY],
          pain:"A PM calls and asks 'what did the CFO actually say about pricing two quarters ago?' — and you have ninety seconds to find it before the call moves on. Same problem before every NDR: pulling the precise prior-call context for the meeting brief.",
          value:"Global Transcript Search surfaces the exact quote in seconds. Transcript Chapters jump straight to the relevant section. AI Chat builds a one-page NDR brief from the last four calls so management meetings start from informed questions, not throat-clearing.",
          impact:"high" },
        { id:"sell-d4", time:"12–4 PM", icon:"📊",
          title:"Modeling, Primers & Theme Work",
          summary:"The deep-work block — model maintenance, sector primers, theme research, and the differentiated content clients pay for",
          tasks:["Model & estimate maintenance","Sector primer drafting","Cross-company theme research","Keyword alert digest review"],
          quartr:true, features:[QF.SEARCH,QF.AI,QF.KEYWORD,QF.HISTORY,QF.MCP],
          pain:"A primer or a theme note is only as good as the source material under it. Reading the relevant chunks of 10+ transcripts to find the three quotes that matter is what burns the afternoon.",
          value:"Keyword Alerts have already flagged the cross-company language you need. AI Chat extracts the exact passages with citations. History Mode shows where management's framing has shifted — the unlock for any narrative-drift theme. Claude MCP runs the synthesis inside your own AI environment so the deliverable lands faster.",
          impact:"high" },
        { id:"sell-d5", time:"4–6 PM", icon:"📋",
          title:"End-of-Day Wrap & Tomorrow's Setup",
          summary:"Field after-close client questions, file the day's notes, and queue tomorrow's priorities so the morning call writes itself",
          tasks:["After-close client Q&A","Note filing & bookmarks","After-hours release watch","Tomorrow's priority list"],
          quartr:false },
      ],
    },

    // Pre-Earnings — the two weeks before a print. PRD §5.1: Earnings Calendar,
    // Pre-Quarter Check-in Prep (NEW Question Builder), Earnings Preview
    // Builder (NEW Preview Workspace), Coverage Pulse, plus the final
    // estimate-lock window.
    PreEarnings: {
      tagline: "The two weeks before the print — preparation that turns into edge",
      goals: ["Calendar discipline", "Differentiated previews", "Estimate confidence"],
      steps: [
        { id:"sell-pre-cal", time:"T–14", icon:"📅",
          title:"Reporting-Cycle Planning",
          summary:"Know what reports when across coverage and adjacent names — release patterns, time zones, and the order in which the cycle will fall on you",
          tasks:["Calendar view across coverage","Watchlist filter","Time-zone aware reporting times","Pre-open vs. post-close release tags"],
          quartr:true, features:[QF.WATCHLIST,QF.SUMMARY,QF.PRESS],
          pain:"Mapping which 18 companies report which week — and which days have three of them at once — is admin that has to happen but adds zero edge. Miss it and you're behind for the cycle.",
          value:"The Watchlist gives you a single calendar across coverage and adjacent names with reporting-time and pre-open/post-close tags. Cycle planning takes minutes, not an afternoon.",
          impact:"medium" },
        { id:"sell-pre-checkin", time:"T–10", icon:"🤝",
          title:"Pre-Quarter Question Build",
          summary:"Build the question list for the pre-quarter check-in call before the company enters its quiet period",
          tasks:["Prior transcript & callback re-read","AI-suggested check-in questions","Channel-check input pulls","Question list export to call notes"],
          quartr:true, features:[QF.SEARCH,QF.HISTORY,QF.AI,QF.TEMPLATE],
          pain:"The pre-quarter check-in is one of the highest-information moments of the quarter — and the question list is usually thrown together the night before from memory. The questions you don't ask are the ones that show up as surprises three weeks later.",
          value:"AI Chat reads the last two transcripts, the prior callback, and your channel-check inputs and drafts a structured check-in question set in minutes. History Mode flags every metric where management's language has shifted — the questions that matter most.",
          impact:"high" },
        { id:"sell-pre-preview", time:"T–7", icon:"🧮",
          title:"Differentiated Preview Build",
          summary:"Reconcile estimates vs. consensus and guidance, lay in peer KPI snapshots, and write the differentiated preview clients will trade off",
          tasks:["Consensus tracker review","Guidance log reconciliation","Peer KPI snapshots","Estimate vs. consensus gap analysis","Preview note publication"],
          quartr:true, features:[QF.AI,QF.HISTORY,QF.SEARCH,QF.SLIDE,QF.TEMPLATE],
          pain:"Writing a differentiated preview means knowing what management said last call, how guidance language has evolved, what peers just printed, and where consensus is wrong — all from memory and a folder of PDFs.",
          value:"AI Chat compiles the guidance trail and the relevant peer KPIs into a structured preview workspace. History Mode flags every line where guidance language has shifted. Slide Search surfaces the exact bridge slide from last quarter. The preview is built in 30 minutes — and it's better than the rushed version.",
          impact:"critical" },
        { id:"sell-pre-pulse", time:"Ongoing", icon:"🔍",
          title:"Cross-Coverage Signal Watch",
          summary:"What clients have been asking, what peers are saying, what the alt-data shows — the running context that makes the preview defensible",
          tasks:["Client-call theme tracking","Peer transcript search","Keyword alert digest","Cross-coverage signal review"],
          quartr:true, features:[QF.KEYWORD,QF.SEARCH,QF.MENTION,QF.MCP],
          pain:"The signals that should sharpen your preview — a peer flagging the same demand weakness, a customer mentioning your covered name, a competitor walking back a target — are buried in calls you didn't cover. By the time you find them, the preview is already out.",
          value:"Keyword Alerts run passively across 14,000+ companies and flag the exact quote the moment it's said. Mentioned By catches every reference to your covered names. Claude MCP synthesises the cycle's signals into a structured pulse digest — your preview lands with cross-coverage evidence consensus doesn't have.",
          impact:"high" },
        { id:"sell-pre-lock", time:"T–3", icon:"🔒",
          title:"Model Finalisation & Estimate Lock",
          summary:"Lock estimates, stress-test the model, and align the sales team in the final 72 hours before results drop",
          tasks:["Final model update","Estimate vs. consensus reconciliation","Sales team alignment","Client pre-call briefings"],
          quartr:true, features:[QF.AI,QF.HISTORY,QF.SEARCH],
          pain:"Locking estimates without a clean view of where guidance has shifted — and what management has subtly walked back — leads to surprises on the print. The miss is rarely the headline; it's a line nobody flagged.",
          value:"AI Chat extracts every guidance comment from the last two calls on demand. History Mode flags exactly where management's language has changed — which is usually the best signal for estimate direction.",
          impact:"medium" },
      ],
    },

    // Earnings (live) — PRD §5.2. The print itself. Four moments: Live Print
    // (NEW First-Look Scaffold), Live Earnings Call, Callback Prep (NEW
    // Callback Generator), and Read-Through Radar (NEW Read-Through Engine).
    EarningsDay: {
      tagline: "The print itself — Reg FD compresses every minute. Speed without sacrificing depth.",
      goals: ["First-look in <15 min", "Live-call signal extraction", "Callback edge", "Read-throughs across coverage"],
      steps: [
        { id:"sell-ed-print", time:"Press Release", icon:"⚡", isCore:true,
          title:"First-Look Note Under Reg FD",
          summary:"Press release just dropped. Reg FD says nothing leaves your desk until you're in print. Every minute to first-look is client mind-share — and the scaffold is what makes 12 minutes possible",
          tasks:["Real-time press release ingestion","KPI extraction & variance vs. estimates","Pre-populated first-look scaffold","Pull-quotes ready to insert","Sales-desk distribution"],
          quartr:true, features:[QF.PRESS,QF.NAV,QF.AI,QF.SUMMARY,QF.TEMPLATE],
          pain:"Reg FD makes the first-look note non-negotiable: until you're in print, you cannot speak to a client about the result. The window between press release and call start is 30–45 minutes. Building a publishable note in that window — with KPI extraction, variance vs. estimates, and the right pull-quotes — is what separates the analysts whose first-looks get read from the ones whose don't.",
          value:"The press release sits alongside prior transcripts and slides in one unified event view. AI Chat extracts the headline KPIs and computes variance vs. estimates and consensus instantly. Prompt Templates pre-populate a first-look scaffold; pull-quotes drop in cleanly. The first-look ships before the call even starts.",
          impact:"critical" },
        { id:"sell-ed-call", time:"Call Live", icon:"📡", isCore:true,
          title:"Live Call Tracking & Q&A Capture",
          summary:"On the call, queued for a question, tracking what management actually said in real time — with peer context one click away",
          tasks:["Live transcript with chapter markers","Real-time keyword & sentiment flags","Queued-question prompter","Peer-quarter side panel"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SPLIT,QF.CHAPTERS,QF.PRESS,QF.NAV],
          pain:"Following the prepared remarks, scanning Q&A for the signal, holding your queued question in your head, and cross-checking what a peer said last week — at the same time, in real time — is a four-screen problem on traditional tools.",
          value:"AI Chat on Live Events answers your question on the live transcript as management is still speaking. Split-View pins the press release, slides, and prior-quarter transcript next to the live call. Transcript Chapters flag every shift in topic. Your queued question lands sharper because you actually heard the answer to the previous one.",
          impact:"critical" },
        { id:"sell-ed-callback", time:"Post-Call", icon:"🎯", isCore:true,
          title:"Callback Question Build",
          summary:"The private Q&A immediately after the public call. Highest information density of the quarter. The question set is what determines what you actually learn",
          tasks:["Auto-generated callback questions","Live-call gap detection","Modeling-point prompts","Prior-callback theme history"],
          quartr:true, features:[QF.LIVE_AI,QF.AI,QF.HISTORY,QF.SEARCH],
          pain:"The callback is one of the most differentiated moments Quartr already serves — and the question set is usually built in the 10 minutes between the public call ending and the callback starting. The questions you skip are the ones that would have told you what's actually going on.",
          value:"The Callback Generator reads the live call transcript, identifies the modeling and strategy gaps the prepared remarks didn't fill, and drafts a callback question set conditioned on prior-callback themes. You walk into the callback with a structured question list — and walk out with the answers that move the model.",
          impact:"critical" },
        { id:"sell-ed-readthru", time:"Within Minutes", icon:"🔗", isCore:true,
          title:"Read-Through Radar",
          summary:"This print implies something for another name. FedEx → UPS → retailers. The read-through is how a single print becomes coverage-wide insight",
          tasks:["Auto-detected read-throughs across watchlist","Peer-impact alerts","Supply-chain linkage map","Client read-through note distribution"],
          quartr:true, features:[QF.WATCHLIST,QF.MENTION,QF.AI,QF.KEYWORD,QF.MCP],
          pain:"The most valuable post-print insight is the implication for the name you do cover that didn't print today. Spotting it requires reading the transcript of every peer event — which nobody has time to do during earnings season. By the time the read-through hits the wire, the trade is gone.",
          value:"The Read-Through Engine watches the watchlist for peer prints, auto-detects read-throughs across linked names, and surfaces them as alerts within minutes of the press release. Send a quick client note ahead of the next morning's research call — without waiting for a sales prompt.",
          impact:"high" },
      ],
    },

    // Post-Earnings — PRD §5.3. After the call: publish the full note, brief
    // sales for the next morning, wrap the cycle. Plus client follow-up which
    // straddles publishing and Quarter Wrap.
    PostEarnings: {
      tagline: "Wrap the print — model, note, sales, clients. Then turn it into the next quarter's setup.",
      goals: ["Note publishing", "Sales enablement", "Cycle synthesis"],
      steps: [
        { id:"sell-post-pub", time:"T+1", icon:"📰",
          title:"Full Note Build & Distribution",
          summary:"Update the model, attach the callback notes, and publish the full post-print note with new estimates, rating, and price target",
          tasks:["Model snapshot vs. prior","Transcript pull-quote attach","Callback notes attach","Version history","Full note distribution"],
          quartr:true, features:[QF.AI,QF.HISTORY,QF.UPLOAD,QF.SEARCH,QF.TEMPLATE],
          pain:"The full note is what the client actually trades off. Building it the day after the print — model snapshot, every supporting quote, the callback context, the estimate cascade — under sales-desk pressure to move on to the next reporter is where depth gets sacrificed.",
          value:"AI Chat extracts every KPI and guidance change from the transcript on demand. Upload your prior-quarter model and the new actuals get surfaced line-by-line with citations. Prompt Templates standardise the note structure so depth survives the speed.",
          impact:"critical" },
        { id:"sell-post-brief", time:"Next Morning", icon:"📣",
          title:"Sales Morning Brief",
          summary:"Arm the sales desk for tomorrow's research call: 60-second brief, top three takeaways, the questions sales will get, and the peer reads",
          tasks:["60-second auto-brief","Top-3 takeaways","Top-3 client questions sales will field","Peer reads","Distribution to sales"],
          quartr:true, features:[QF.AI,QF.SUMMARY,QF.TEMPLATE,QF.MCP],
          pain:"Sales hits the morning call with eight reporters' notes in front of them. The note that gets pitched is the one with the cleanest 60-second brief — not the deepest analysis. Building that brief, after the full note, is admin nobody wants but everybody needs.",
          value:"AI Chat compresses your full note into a 60-second brief with top-three takeaways and the three questions sales will field — formatted for the morning call. Claude MCP can run the same compression across every covered name's note in one pass.",
          impact:"high" },
        { id:"sell-post-followup", time:"T+1–3", icon:"📞",
          title:"Client Q&A & Management Access",
          summary:"Field the client questions that go beyond the published note and facilitate management access calls in the days after the print",
          tasks:["Client Q&A calls","Management access facilitation","Key investor briefings","Consensus implication discussion"],
          quartr:true, features:[QF.AI,QF.CHAPTERS,QF.SEARCH],
          pain:"Clients ask follow-ups that go deeper than the note — and the answer requires pulling exact quotes and context from the transcript while the client is still on the line.",
          value:"AI Chat surfaces any transcript quote or management comment on demand. Transcript Chapters jump to the exact section instantly. The follow-up call is sharper than the note.",
          impact:"high" },
        { id:"sell-post-wrap", time:"End of Cycle", icon:"📦",
          title:"Cycle Theme Synthesis",
          summary:"End-of-cycle recap of the coverage: what beat, what missed, the themes that emerged, and the names reporting next week",
          tasks:["Coverage scorecard (beat/miss/in-line)","Cross-company thematic recap","Differentiated view articulation","Next-week preview list"],
          quartr:true, features:[QF.HISTORY,QF.SEARCH,QF.KEYWORD,QF.AI,QF.MCP],
          pain:"The cycle wrap is the most valuable client-facing content of the quarter — and the hardest to write fast. Synthesising the cross-company patterns from 20 prints, while the next cycle is already starting, is what gets cut.",
          value:"Keyword Alerts have been flagging cross-company patterns all cycle. AI Chat synthesises them into a thematic recap. History Mode contextualises every print against prior quarters. Claude MCP turns the cycle's signals into a structured wrap automatically — the differentiated view consensus doesn't have.",
          impact:"critical" },
      ],
    },

    // Non-Earnings — PRD §5.4. The space between earnings waves where today's
    // app under-serves and retention risk peaks. Investor Days, Conferences,
    // Initiations (NEW Initiation Workspace), Coverage Intelligence (NEW
    // Coverage Intelligence Pipeline).
    NonEarnings: {
      tagline: "Between earnings waves — investor days, conferences, initiations, and always-on coverage",
      goals: ["Event coverage", "New-company speed", "Always-on signal"],
      steps: [
        { id:"sell-non-id", time:"May–Sep", icon:"🌟", isCore:true,
          title:"Multi-Year Thesis Build",
          summary:"Multi-hour management deep-dives, often with new long-term targets — the richest content event of the year for any covered name",
          tasks:["Event registration & live coverage","Slide deck ingestion","Long-term target vs. prior","Summary generation","Client webinar prep"],
          quartr:true, features:[QF.LIVE,QF.LIVE_AI,QF.SLIDE,QF.NAV,QF.SUMMARY,QF.HISTORY],
          pain:"Investor Days contain more strategically valuable content than any other event — but they're hours long, and the key signals are buried. Without the right tools, the post-event note is a slide-by-slide recap rather than the strategic re-think it should be.",
          value:"Attend live with AI Chat answering questions on the transcript in real time. Slide Search surfaces the exact bridge from last year's CMD. History Mode compares this year's long-term targets to the prior set, line by line. Publish a deeper note faster than any competitor.",
          impact:"critical" },
        { id:"sell-non-conf", time:"Q3 / Q4", icon:"🎤",
          title:"Off-Script Signal Capture",
          summary:"Bank-hosted conferences with off-schedule management appearances — vetted question lists for fireside chats and group meetings",
          tasks:["Conference calendar","Per-meeting question generator","Prior fireside-chat archive","Cross-company conference theme tracking"],
          quartr:true, features:[QF.LIVE,QF.SEARCH,QF.SUMMARY,QF.MENTION,QF.AI],
          pain:"Conference presentations often contain the most candid management commentary — but most analysts can only cover a fraction of them, and the question list for each meeting gets thrown together in the elevator.",
          value:"Quartr captures conference presentations and firesides across 14,000+ companies. AI Chat builds a vetted question list per meeting from the prior fireside-chat archive. Event Summaries process every covered-company appearance you couldn't attend.",
          impact:"high" },
        { id:"sell-non-init", time:"Quiet Periods", icon:"🆕", isCore:true,
          title:"New-Coverage Build",
          summary:"Learning a new company quickly to publish initiation of coverage. The workspace pre-loads filings, transcript history, peer set, and KPI scaffolding",
          tasks:["Multi-year transcript deep-read","Filings & governance pull","Peer-set scaffolding","KPI history extraction","Banking quiet-period flag","Initiation note drafting"],
          quartr:true, features:[QF.HISTORY,QF.AI,QF.SEARCH,QF.SLIDE,QF.GOVERNANCE,QF.UPLOAD],
          pain:"A proper initiation requires reading years of transcripts, filings, and presentations — a 2–3 week process that drains research resources. Initiations done shallow are initiations that don't move the stock.",
          value:"The Initiation Workspace pre-loads filings, transcript history, peer set, and KPI scaffolding the moment you target a new name. AI Chat compresses 5 years of transcripts into a structured narrative chronology. History Mode maps the evolution of every key metric and management commitment. Banking quiet-period flag sits on top so nothing gets published it shouldn't.",
          impact:"critical" },
        { id:"sell-non-intel", time:"Always-On", icon:"⚙️", isCore:true,
          title:"Always-On Coverage Watch",
          summary:"Passive monitoring of coverage names between events — filings, management changes, peer events, theme tracking, all delivered as alerts",
          tasks:["Filing alerts","Management-change alerts","Peer-event alerts","Theme tracking","Weekly intelligence digest via MCP"],
          quartr:true, features:[QF.KEYWORD,QF.MENTION,QF.WATCHLIST,QF.MCP],
          pain:"The most valuable signals between earnings — a company in your supply chain flagging demand weakness, a competitor announcing a surprise buyback, a management team using 'restatement' for the first time — are buried in events you didn't attend. By the time the rival sellside note lands, the edge is gone. This gap is where Quartr's daily-use case has historically been weakest, and where retention risk peaks.",
          value:"Configure Keyword Alerts for your sector's critical terms and risk signals. Quartr monitors every public earnings call and event across 14,000+ companies and delivers alerts straight from the source. Claude MCP automatically synthesises the week's signals into a structured intelligence digest. The differentiated view clients pay for — built passively, between earnings.",
          impact:"high" },
      ],
    },
  },
};

// ─── Sales Playbooks ───────────────────────────────────────────────────────────
export const PLAYBOOKS = {
  IR: {
    Daily:       { pitch:"Lead with the morning — 'How do you find out when a competitor mentions your company overnight?' The Watchlist + Mentioned By demo is the fastest route to an 'I need this' moment.", top:["ir-d1","ir-d3"] },
    Weekly:      { pitch:"The weekly peer intelligence report is the single most tangible time-save. Ask: 'How long does your team spend compiling the weekly competitor digest?' Then show Quartr does it in 10 minutes.", top:["ir-w2","ir-w4"] },
    Monthly:     { pitch:"Hit the narrative audit pain. IR Directors know their story may have drifted — they just don't have a process to catch it. Demo the AI Chat narrative drift prompt: 8 quarters, analysed in 2 minutes.", top:["ir-m2","ir-m-narrative"] },
    Yearly:      { pitch:"Earnings cycle and Investor Day are the two events IR teams fear most. Show AI Chat on Live Events for earnings, then the re-rating reverse engineering prompt for Investor Day planning.", top:["ir-y2","ir-y4"] },
    PreEarnings: { pitch:"The Q&A document is where earnings are won or lost. Ask: 'How do you currently prepare for the questions you haven't been asked before?' Then show AI Chat building the full Q&A anticipation brief from peer transcripts.", top:["ir-pre1","ir-pre2"] },
    EarningsDay: { pitch:"The hardest 6 hours in IR. Demo AI Chat on Live Events monitoring a peer call simultaneously with your own — and the instant Event Summary for the post-call management debrief.", top:["ir-ed2","ir-ed3"] },
    PostEarnings:{ pitch:"The narrative audit is the most overlooked IR workflow. Ask: 'Do you systematically check whether your story drifted this quarter?' Then show the post-call narrative audit prompt in AI Chat.", top:["ir-post1","ir-post3"] },
  },
  Buyside: {
    Daily:       { pitch:"Start with earnings day: 'What does your workflow look like when you have 3 covered companies reporting the same morning?' Demo AI Chat on Live Events — questions answered on the live transcript before Q&A ends.", top:["buy-d2","buy-d3"] },
    Weekly:      { pitch:"The Automated Keyword Intelligence Feed is the sleeper feature. Ask: 'How do you currently find out when a company in your supply chain mentions something relevant?' Then show passive alerts delivering signals before the sellside note.", top:["buy-w-keyword","buy-w2"] },
    Monthly:     { pitch:"Thesis stress-testing via Document Upload is a powerful differentiator. 'Upload your sellside report and find where the analyst's assumptions diverge from what management actually said.' Then layer in MCP.", top:["buy-m2","buy-m3"] },
    Yearly:      { pitch:"Investor Day season is underserved — most PMs can't process all the CMDs they want to attend. Lead with: 'How many did you miss last year?' Then demo AI Chat answering questions on a live Investor Day transcript.", top:["buy-y1","buy-y2"] },
    PreEarnings: { pitch:"Ask: 'How long does it take you to prepare for earnings on a name you haven't fully re-read in 2 quarters?' Then show History Mode compressing 8 quarters into a structured briefing in 90 seconds.", top:["buy-pre1","buy-pre2"] },
    EarningsDay: { pitch:"The pre-market is the most valuable 45 minutes of an analyst's quarter. Demo AI Chat on the press release before the call starts — model update inputs ready before management has said a word.", top:["buy-ed1","buy-ed2"] },
    PostEarnings:{ pitch:"'Where do you lose the most time after earnings?' The answer is always consensus interrogation. Demo Upload + AI Chat on a sellside note — divergences from the transcript with citations, in under a minute.", top:["buy-post1","buy-post2"] },
  },
  Sellside: {
    Daily:       { pitch:"The morning research call and the email blast are the daily moment of truth. Ask: 'How does the morning blast get written?' Demo AI Chat with Prompt Templates building it from prior call notes, plus a Mentioned By feed that catches every overnight reference to your covered names.", top:["sell-d2","sell-d4"] },
    PreEarnings: { pitch:"The pre-quarter check-in and the preview are where the cycle is won. Ask: 'How does your earnings preview get built?' Then show AI Chat assembling the guidance trail, peer KPIs, and shifted-language flags into a structured Preview Workspace in 30 minutes.", top:["sell-pre-preview","sell-pre-checkin"] },
    EarningsDay: { pitch:"Reg FD makes the first-look non-negotiable. Demo the First-Look Scaffold — press release ingestion, KPI variance, scaffold ready in under 12 minutes. Then layer in the Callback Generator: question set built from the gaps in the public call.", top:["sell-ed-print","sell-ed-callback"] },
    PostEarnings:{ pitch:"The full note and the morning brief are different deliverables for different audiences. Demo the Note Publishing Hub for the trade-able note, then the Morning Call Brief — same content, compressed for sales — and watch the lightbulb come on for any director of research.", top:["sell-post-pub","sell-post-wrap"] },
    NonEarnings: { pitch:"Non-earnings DAU is the retention gap. Lead with the Coverage Intelligence pipeline — passive Keyword Alerts across 14,000+ companies — then show the Initiation Workspace pre-loading filings and peer set the moment a new name is targeted. This is where seats get retained between cycles.", top:["sell-non-intel","sell-non-init"] },
  },
};


export function findStep(icp, period, id) {
  return (WORKFLOWS[icp]?.[period]?.steps || []).find(s => s.id === id);
}
